
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 19 09:37:56 ART 2014
//----------------------------------------------------

package compilacionFormulas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 10;
  public static final int EXISTE = 2;
  public static final int PC = 9;
  public static final int PA = 8;
  public static final int ERROR = 14;
  public static final int IDVAR = 11;
  public static final int PARATODO = 3;
  public static final int EOF = 0;
  public static final int IMPLICACION = 7;
  public static final int IDPRED = 13;
  public static final int DISYUNCION = 5;
  public static final int CONJUNCION = 6;
  public static final int error = 1;
  public static final int IDFUNC = 12;
  public static final int NEGACION = 4;
}

